// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoditriPekanbaru.Data;

#nullable disable

namespace RoditriPekanbaru.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250523181515_UpdateUserSystem")]
    partial class UpdateUserSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("RoditriPekanbaru.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Level = "Admin",
                            NamaLengkap = "Administrator",
                            Password = "admin123",
                            Username = "admin"
                        },
                        new
                        {
                            AdminId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Level = "User",
                            NamaLengkap = "User Biasa",
                            Password = "user123",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("RoditriPekanbaru.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaCustomer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoTelepon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pekerjaan")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalDaftar")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RoditriPekanbaru.Models.Mobil", b =>
                {
                    b.Property<int>("MobilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GambarMobil")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kondisi")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Merek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoMesin")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoPolisi")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoRangka")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tahun")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TanggalInput")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warna")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("MobilId");

                    b.ToTable("Mobils");
                });

            modelBuilder.Entity("RoditriPekanbaru.Models.TransaksiPenjualan", b =>
                {
                    b.Property<int>("TransaksiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Admin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaraPembayaran")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Diskon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HargaJual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MobilId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoFaktur")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SisaPembayaran")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StatusMobil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusPembayaran")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalTransaksi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalBayar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UangMuka")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransaksiId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MobilId");

                    b.ToTable("TransaksiPenjualans");
                });

            modelBuilder.Entity("RoditriPekanbaru.Models.TransaksiPenjualan", b =>
                {
                    b.HasOne("RoditriPekanbaru.Models.Customer", "Customer")
                        .WithMany("TransaksiPenjualan")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoditriPekanbaru.Models.Mobil", "Mobil")
                        .WithMany("TransaksiPenjualan")
                        .HasForeignKey("MobilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Mobil");
                });

            modelBuilder.Entity("RoditriPekanbaru.Models.Customer", b =>
                {
                    b.Navigation("TransaksiPenjualan");
                });

            modelBuilder.Entity("RoditriPekanbaru.Models.Mobil", b =>
                {
                    b.Navigation("TransaksiPenjualan");
                });
#pragma warning restore 612, 618
        }
    }
}
